-- Metadata cho hàng DM do user thêm (+) — chạy trên Supabase SQL Editor nếu cần
ALTER TABLE "DM_CONG_VIEC" ADD COLUMN IF NOT EXISTS nguon text DEFAULT 'HE_THONG';
ALTER TABLE "DM_CONG_VIEC" ADD COLUMN IF NOT EXISTS trang_thai_dm text DEFAULT 'MAC_DINH';
ALTER TABLE "DM_CONG_VIEC" ADD COLUMN IF NOT EXISTS tao_boi_email text;
ALTER TABLE "DM_CONG_VIEC" ADD COLUMN IF NOT EXISTS tao_luc timestamptz;

COMMENT ON COLUMN "DM_CONG_VIEC".nguon IS 'HE_THONG | NVKS_USER';
COMMENT ON COLUMN "DM_CONG_VIEC".trang_thai_dm IS 'MAC_DINH | CHO_KIEM | CHUAN';
